SECRET_KEY: "This is an INSECURE secret!! DO NOT use this in production!!"
FLASK_ENV: development
TESTING: True

STATIC_FOLDER: static
TEMPLATES_FOLDER: templates

USER_APP_NAME: "CSEP app"
USER_ENABLE_EMAIL: "False"
USER_ENABLE_USERNAME: "True"
USER_REQUIRE_RETYPE_PASSWORD: "False"

MAIL_SERVER : "smtp.univie.ac.at"
MAIL_PORT : 465
MAIL_USE_SSL : true
MAIL_USE_TLS : false
MAIL_USERNAME : "ladenburge19@univie.ac.at"
MAIL_PASSWORD : "Nope"
MAIL_DEFAULT_SENDER : "'Cybersecurity Scenario Education Platform' <csep@univie.ac.at>"