# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Django.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest
services:
  - mongodb:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Installing requirements..."
    - pip install -r requirements.txt

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - python3 -m unittest source/tests

deploy-dev:
  stage: deploy
  script:
    - echo "The code is now deployed"

deploy-prod:
  stage: deploy
  script:
    - echo "The code is now deployed on prod!"