{'stories': [{'title': 'Introduction', 'injects': {'introduction': {'label': 'Introduction',
                                                                    'text': 'Hello Player! In this scenario_design you will indulge in your dark side: playing through the eyes of an expert social engineer. Your first target is Jaffa Bezous, the Chief Operating Officer of a global bookstore.What will your preparation look like?',
                                                                    'slug': 'introduction', 'media_path': '',
                                                                    'choices': [{'label': 'Do nothing',
                                                                                 'outcome': {'next_inject': None,
                                                                                             'variable_changes': []}}],
                                                                    'condition': None,
                                                                    'next_inject': {'label': 'Second Inject',
                                                                                    'text': "Interesting choice... let's see, if your preparation pays off. How will you proceed?",
                                                                                    'slug': 'second-inject',
                                                                                    'media_path': '', 'choices': [],
                                                                                    'condition': None,
                                                                                    'next_inject': None}},
                                                   'second-inject': {'label': 'Second Inject',
                                                                     'text': "Interesting choice... let's see, if your preparation pays off. How will you proceed?",
                                                                     'slug': 'second-inject', 'media_path': '',
                                                                     'choices': [], 'condition': None,
                                                                     'next_inject': None}},
              'entry_node': 'introduction'}, {'title': 'final chapter', 'injects': {
    'almost-done': {'label': 'Almost Done', 'text': 'Well done, you are almost there!', 'slug': 'almost-done',
                    'media_path': '', 'choices': [
            {'label': 'Walk straight ahead', 'outcome': {'next_inject': None, 'variable_changes': []}},
            {'label': 'Turn Right', 'outcome': {'next_inject': None, 'variable_changes': []}}], 'condition': None,
                    'next_inject': {'label': 'Finish', 'text': 'You have completed the test scenario_design!',
                                    'slug': 'finish', 'media_path': '', 'choices': [], 'condition': None,
                                    'next_inject': None}},
    'finish': {'label': 'Finish', 'text': 'You have completed the test scenario_design!', 'slug': 'finish', 'media_path': '',
               'choices': [], 'condition': None, 'next_inject': None}}, 'entry_node': 'almost-done'}],
 'learning_objectives': '', 'required_knowledge': '', 'target_group': None,
 'variables': {'Budget': {'name': 'Budget', 'datatype': 'numeric', 'is_private': False, 'value': 10000},
               'Financial Loss': {'name': 'Financial Loss', 'datatype': 'numeric', 'is_private': False, 'value': 0},
               'Reputation Damage': {'name': 'Reputation Damage', 'datatype': 'textual', 'is_private': False,
                                     'value': 'None'},
               'Internal Variable': {'name': 'Internal Variable', 'datatype': 'boolean', 'is_private': False,
                                     'value': False}}}
