---
DATABASE:
  DEV:
    DB_NAME: yourDBnameDEV
    DB_HOST: "mongodb://localhost:27017"
  PROD:
    DB_NAME: yourDBnamePROD
    DB_HOST: "mongodb+srv://db_user:db_password@your-mongodb-instance.mongodb.net"
  TEST:
    DB_NAME: yourDBnameTEST
    DB_HOST: "mongodb://localhost:27018"

FLASK:
  ENV: development
  DEBUG: True
  MAIL_SERVER: mail.yourserver.com
  MAIL_PORT: 465
  MAIL_USERNAME: your.name@yourserver.com
  MAIL_PASSWORD: "Your password."
  MAIL_DEFAULT_SENDER: "'CSEP Platform' <csep-platform@yourserver.com>"
  MAIL_USE_SSL: true
  MAIL_USE_TLS: true

  USER_APP_NAME: "CSEP platform"
  USER_ENABLE_EMAIL: "False"
  USER_ENABLE_USERNAME: "True"
  USER_REQUIRE_RETYPE_PASSWORD: "False"

  SECRET_KEY: "some_secret"

  STATIC_FOLDER: "static"
  TEMPLATES_FOLDER: "templates"
  UPLOAD_FOLDER: "static/assets/uploads"
